name: "sons-of-liberty"
services:
  postgres-sol:
    image: postgres:latest
    container_name: postgres-sol
    hostname: postgres-sol
    environment:
      - POSTGRES_PASSWORD=loco
      - POSTGRES_USER=loco
      - POSTGRES_DB=sons-of-liberty_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  sons-of-liberty:
    name: "sons-of-liberty"
