//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "balances")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bitcoin_balance_sats: i64,
    pub bitcoin_balance_usd: Decimal,
    pub bitcoin_price: Decimal,
    pub contract_balance_sats: i64,
    pub contract_balance_usd: Decimal,
    pub pnl_sats: i64,
    pub pnl_usd: Decimal,
    pub num_contracts: i64,
    pub name: String,
    pub network: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
