//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "keychain")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub wallet_name: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub keychainkind: String,
    #[sea_orm(column_type = "Text")]
    pub descriptor: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub descriptor_id: Vec<u8>,
    pub last_revealed: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
